name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ok
        run: "true"
      - name: oke
        run: "true"
      - name: check
        if: ${{ failure() }}
        run: echo hello
