name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-windows:
    runs-on: windows-2022
    steps:
      - run: |
          'C:\Program Files\Docker\Docker\DockerCli.exe' -h
      - run: docker info
      - run: docker run -d --rm --name test-postgres -p 5432 postgres:alpine
      - run: docker port test-postgres
      - run: sleep 10
      - run: docker logs test-postgres
      - run: docker rm -fv test-postgres
      - run: docker info
