name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/12830755177/locations/global/workloadIdentityPools/lala/providers/lala-github
        service_account: test-sa@win-test-389210.iam.gserviceaccount.com
    - uses: google-github-actions/setup-gcloud@v1
    - name: lala
      run: |
        gcloud auth list
        curl -s "https://oauth2.googleapis.com/tokeninfo?access_token=$(gcloud auth print-access-token)"
