name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken()
            const part = token.split('.')
            const decode = str => atob(str.replace(/-/g, '+').replace(/_/g, '/'))
            console.log(decode(part[0]))
            console.log(decode(part[1]))
