name: CI
on:
  push: {}
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo github.event_name ${{ github.event_name }}
          echo github.event_path ${{ github.event_path }}
          echo github.run_id ${{ github.run_id }}
          echo github.run_number ${{ github.run_number }}
