name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: commit-${{ github.sha }}
          restore-keys: commit-
          path: ~/.npm
      - name: run script
        run: |
          npm init -y
          npm install express
