name: CI
on:
  push:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    env: 
      REGISTRY: asia-southeast2-docker.pkg.dev/test-cc57d07c78f1/docker
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/190151941575/locations/global/workloadIdentityPools/github-action/providers/github-oidc
        service_account: github-action-rmc@test-cc57d07c78f1.iam.gserviceaccount.com
    - uses: google-github-actions/setup-gcloud@v1
    - name: Setup docker auth
      run: gcloud auth configure-docker "${REGISTRY%%/*}" --quiet
    - name: cek token
      run: |
        curl -sSLf "https://oauth2.googleapis.com/tokeninfo?access_token=$(gcloud auth print-access-token)"
        cat $GOOGLE_APPLICATION_CREDENTIALS
    - name: lala
      run: |
        docker pull wint/httpecho
        docker tag wint/httpecho "${REGISTRY}/httpecho"
        docker push "${REGISTRY}/httpecho"
        gcloud run deploy rmc \
        --region asia-southeast2 \
        --allow-unauthenticated \
        --image wint/httpecho \
        --cpu-boost \
        --no-cpu-throttling \
        --cpu 80m \
        --memory 128Mi \
        --concurrency 1 \
        --min-instances 0 --max-instances 100 \
        --service-account cloudrun-rmc@test-cc57d07c78f1.iam.gserviceaccount.com \
        --port 1234 \
        --ingress internal-and-cloud-load-balancing \
        --update-env-vars=ENV=production
