name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          docker buildx version
          docker buildx inspect
