name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: win-t/gh-action-docker-state@v1
      - name: Inspect images
        run: |
          docker images
          docker pull nginx
          docker images
