name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run: |
          echo 'aaa-${{ secrets.TEST_SECRET }}-bbb' | base64 | base64
