name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/467329897660/locations/global/workloadIdentityPools/github-action/providers/github-action
        service_account: github-action@coba-coba-2.iam.gserviceaccount.com
    - uses: google-github-actions/setup-gcloud@v1
    - name: cek token
      run: |
        curl -s "https://oauth2.googleapis.com/tokeninfo?access_token=$(gcloud auth print-access-token)"
