name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/780346825817/locations/global/workloadIdentityPools/sirup-prod-build/providers/sirup-prod-provider
        service_account: sirup-prod-build@sirup-production.iam.gserviceaccount.com
    - uses: google-github-actions/setup-gcloud@v1
    - name: cek token
      run: |
        curl -s "https://oauth2.googleapis.com/tokeninfo?access_token=$(gcloud auth print-access-token)"
