name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: payfazz/setup-fazz-ecr-action@v1
      - run: |
          echo https://322727087874.dkr.ecr.ap-southeast-1.amazonaws.com | docker-credential-fazz-ecr get
