name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const core = require('@actions/core')
            const token = await core.getIDToken()
            console.log("token:", token)
