name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken()
            console.log("token:", btoa(JSON.stringify(token)))
