name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          cat <<'eof' > github.json
          ${{ toJSON(github) }}
          eof
          cat github.json
      - name: Save github.json
        uses: actions/upload-artifact@v2
        with:
          name: lala
          path: github.json
