name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hehehe
        uses: ./.github/asdf
      - name: Build
        run: |
          mkdir /opt/asdf
          cd /opt/asdf
          ls -lha
