name: test cron

on:
  schedule:
    - cron: '45 3 * * *' # 3:45 UTC -> 10:45 Jakarta

jobs:
  lala:
    runs-on: ubuntu-latest
    steps:
      - name: lala
        run: |
          echo Hello world
